version: '3'

services:
  imperugo.wpc.netflix.apis:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  quickstartidentityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
